Gazebo cleanup
moose-cpr/moose_simulator pull request #1
Opened 2019-11-28 20:09 UTC by dniewinski

2019-11-28 20:09 UTC, dniewinski commented
@tonybaltovski

2019-11-29 00:08 UTC, tonybaltovski requested changes

2019-11-29 00:08 UTC, tonybaltovski commented on moose_gazebo/scripts/dummy_keyswitch.py
> +#!/usr/bin/env python
Should install this in CMakeLists.

2019-11-29 20:48 UTC, tonybaltovski commented
Last nit, otherwise LGTM.  Thanks.

2019-11-29 20:48 UTC, merged